# Basic
title: 品味
subtitle: 一个不一样的美食餐厅
welcome_message: <a href="#" target="_blank">各位客官，欢迎光临品味店！</a>
description: 总有一种味道属于你
creator: Jason

url: "http://www.tastecloud.club"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: red

# The blog button should not be removed.
blog_button:
    title: Blog
    description: Visit blog

# Navigation buttons in the front page.
nav:
    - {title: Projects, description: My Projects, url: 'http://www.tastecloud.club'}
    # - {title: Another Button, description: A button, url: 'http://example.com'}

# Pagination
gems: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
comment:
    disqus: vno-jekyll
    # duoshuo: 
    
# Social
social:
    weibo: onevcat
    github: onevcat
    twitter: onevcat
    gplus: 107108267983477358170
    mail: onev@onevcat.com

# Google Analytics
ga:
    # id: your_ga_id
    # host: your_host
